### ISSUE TITLE
prevent i18next warnings when using i18next-http-backend

### ISSUE THREAD

**Issue by adrai** [mbarzda/solid-i18next#13]
Is there a way to prevent these i18next warnings when using a backend plugin, like i18next-http-backend?

<img width="796" alt="image" src="https://user-images.githubusercontent.com/1086194/161702809-f1e8bb15-a7d6-4ab3-ac5e-d4d8d0e6c332.png">

example: https://codesandbox.io/s/solidjs-starter-template-forked-xz4ti6

fyi: react-i18next for example is using the Suspense mechanism to not render the texts until i18next is initialized and the appropriate namespace is loaded, or alternatively is offering a ready flag, when Suspense is not used: https://react.i18next.com/latest/usetranslation-hook#not-using-suspense

**Comment by mbarzda** [comment]
Hi @adrai . Currently there is no solution for suppress these debug warnings. The case is interesting, maybe will do something with it in the future. I see that text, after load, is set, so for production it is working as expected.

**Comment by mbarzda** [comment]
Now debug warning is not thrown on initial load

**Comment by adrai** [comment]
Thank you @mbarzda I updated the above codesandbox example to v1.1.3 but it still shows the warnings: https://codesandbox.io/s/solidjs-starter-template-forked-krfhwe?file=/src/App.js

What should be exactly changed?
Isn't there something like a ready flag, like in react? https://react.i18next.com/latest/usetranslation-hook#not-using-suspense
or a fallbackComponent for the TransProvider that would be used when the translations are not yet loaded?
i.e. 
```
<TransProvider options={i18nextOptions} fallback="Loading...">
      <App />
</TransProvider>
```
