### ISSUE TITLE
SSR/solid-start support

### ISSUE THREAD

**Issue by lizclipse** [mbarzda/solid-i18next#27]
I'm trying to use this library with solid-start, and when the app is rendered on the server I get this error thrown at me:

`__vite_ssr_import_0__.memo is not a function`

It looks like it's because the library is pre-compiled to be client only, as I can ignore the error and run it fine within the browser. Could this library be updated to support SSR?

Solid-start seems to distribute its components by just shipping the pure TS files, so that could be all that's needed?

**Comment by BierDav** [comment]
Are there any plans to fix this?

**Comment by mbarzda** [comment]
I released new version v1.3.0 with artifacts for browser and server https://www.npmjs.com/package/@mbarzda/solid-i18next/v/1.3.0?activeTab=code
